/**
 * Creates one sample invoice in MongoDB for preview/testing.
 * Usage: npx tsx src/scripts/seedSampleInvoice.ts
 */
import "dotenv/config";
import mongoose from "mongoose";
import { getEnv } from "../config/env.js";
import { InvoiceModel } from "../models/Invoice.model.js";
import { UserModel } from "../models/User.model.js";
import { BatchModel } from "../models/Batch.model.js";
import { INVOICE_SOURCE, INVOICE_STATUS } from "@funt-platform/constants";

async function main() {
  const { mongoUri } = getEnv();
  await mongoose.connect(mongoUri);

  const student = await UserModel.findOne({}).sort({ createdAt: 1 }).lean().exec();
  const batch = await BatchModel.findOne({}).sort({ createdAt: -1 }).lean().exec();

  if (!student || !batch) {
    console.error("Need at least one user and one batch in the database.");
    process.exit(1);
  }

  const day = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const prefix = `FUNT-INV-${day}`;
  const count = await InvoiceModel.countDocuments({ invoiceNumber: { $regex: `^${prefix}` } });
  const invoiceNumber = `${prefix}-${String(count + 1).padStart(4, "0")}`;

  const snaps = (batch as { courseSnapshots?: Array<{ courseId?: string; title?: string; enrollmentPriceInPaise?: number }> }).courseSnapshots ?? [];
  const snap = snaps[0];
  const courseTitle = String(snap?.title ?? "Course");
  const amountInPaise = Math.max(0, Number(snap?.enrollmentPriceInPaise ?? 499900));
  const discountInPaise = 0;
  const totalInPaise = amountInPaise - discountInPaise;

  const doc = await InvoiceModel.create({
    invoiceNumber,
    studentId: String(student._id),
    batchId: String(batch._id),
    courseId: String(snap?.courseId ?? ""),
    source: INVOICE_SOURCE.MANUAL_ADMIN,
    status: INVOICE_STATUS.ISSUED,
    amountInPaise,
    discountInPaise,
    totalInPaise,
    currency: "INR",
    lineDescription: `Course enrollment — ${courseTitle} (${(batch as { name?: string }).name ?? "Batch"})`,
    studentName: String((student as { name?: string }).name ?? ""),
    studentEmail: String((student as { email?: string }).email ?? ""),
    studentUsername: String((student as { username?: string }).username ?? ""),
    batchName: String((batch as { name?: string }).name ?? ""),
    courseTitle,
    notes: "Sample invoice generated by seed script",
    issuedAt: new Date(),
    createdBy: String(student._id),
  });

  console.log(JSON.stringify({ id: String(doc._id), invoiceNumber: doc.invoiceNumber }, null, 2));
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
