import { z } from "zod";

export const createLetterSchema = z.object({
  type: z.enum(["OFFER_LETTER", "EXPERIENCE_LETTER"]),
  recipientName: z.string().min(1, "Recipient name is required").max(200),
  recipientEmail: z.string().email().optional().or(z.literal("")),
  recipientMobile: z.string().max(15).optional(),
  recipientGender: z.enum(["Mr", "Ms", "Mrs", "Mx"]).optional(),
  employmentType: z.string().min(1, "Employment type is required").max(50),
  department: z.string().min(1, "Department is required").max(100),
  designation: z.string().min(1, "Designation is required").max(200),
  joiningDate: z.string().min(1, "Joining date is required"),
  endDate: z.string().optional(),
  duration: z.string().max(50).optional(),
  stipend: z.string().max(200).optional(),
  stipendAmount: z.number().min(0).optional(),
  ctc: z.string().max(200).optional(),
  location: z.string().max(200).optional(),
  reportingTo: z.string().max(200).optional(),
  responsibilities: z.string().max(10000).optional(),
  timings: z.string().max(500).optional(),
  termsAndConditions: z.string().max(10000).optional(),
  performanceSummary: z.string().max(5000).optional(),
  dutiesDescription: z.string().max(5000).optional(),
  signatoryName: z.string().max(200).optional(),
  signatoryRole: z.string().max(200).optional(),
  signatoryImageUrl: z.string().url().optional().or(z.literal("")),
  stampImageUrl: z.string().url().optional().or(z.literal("")),
  linkedLetterId: z.string().max(50).optional(),
  acceptanceDeadlineDays: z.number().int().min(1).max(30).optional(),
});
